# _config.yml

# === 基本信息 ===
title: Jeffrey Liao's Blog
baseurl: "/M4n1puLatE.github.io"  # 如果你的项目是 username.github.io/repo-name，则填 "/repo-name"
url: "https://m4n1pulate.github.io/"  # GitHub Pages URL（不含 baseurl）

# === Jekyll 设置 ===
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


markdown: commonmark
commonmark:
  options:
    footnotes: true
    gfm_quirks: "all"
  extensions:
    - autolink
    - strikethrough
    - table
    - tagfilter



# === Excludes ===
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

