safe: true                 # 禁用插件
lsi: false
highlighter: none
gist:
  noscript: false
kramdown:
  math_engine: null

# 不处理任何文件
include: []               # 不包含任何额外文件
exclude: []               # 不排除任何文件
keep_files: []            # 不保留任何文件

# 完全禁用
theme: null               # 不使用主题
plugins: []               # 不使用插件
